<a href="https://colab.research.google.com/github/bforoura/IDS/blob/main/ex_9_13.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### **Pandas DataFrame**

In [109]:
# used for data analysis in Python

import pandas as pd

In [110]:
# a small dataset

data = {'employee': ['Jack', 'Mary', 'Joe', 'Sally'], 'age':[54, 26, 22, 31], 'salary': [123000, 154000, 75000, 45000]}

In [111]:
# create a data frame for the data

df = pd.DataFrame(data)

In [112]:
# display the dataframe
# print(df) works just as well

df

  employee  age  salary
0     Jack   54  123000
1     Mary   26  154000
2      Joe   22   75000
3    Sally   31   45000

In [113]:
# print metadata about the frame

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   employee  4 non-null      object
 1   age       4 non-null      int64
 2   salary    4 non-null      int64
dtypes: int64(2), object(1)
memory usage: 224.0+ bytes

In [114]:
# print the first column using associative addressing

df['employee']

0     Jack
1     Mary
2      Joe
3    Sally
Name: employee, dtype: object

In [115]:
# select column with index position 0

df.iloc[:, 0]

0     Jack
1     Mary
2      Joe
3    Sally
Name: employee, dtype: object

In [116]:
# select columns with index positions 1 and 2

df.iloc[:, [1, 2]]

   age  salary
0   54  123000
1   26  154000
2   22   75000
3   31   45000

In [117]:
# select columns with index positions as a range

df.iloc[:, 1:3]

   age  salary
0   54  123000
1   26  154000
2   22   75000
3   31   45000

In [118]:
# find min, max, and mean of age

min = df['age'].min()
max = df['age'].max()
mean = df['age'].mean()
var = df['age'].var()
std = df['age'].std()

print ("Min age: , Max age: , Mean age: , Var age, Std age: ", min, max, mean, var, std)

Min age: , Max age: , Mean age: , Var age, Std age:  22 54 33.25 204.91666666666666 14.314910641239317

In [119]:
# minmax scaling

(df['age'] - min) / (max - min)

0    1.00000
1    0.12500
2    0.00000
3    0.28125
Name: age, dtype: float64

In [120]:
# z-score scaling

(df['age'] - mean) / (std)          # z-score normalize

0    1.449538
1   -0.506465
2   -0.785894
3   -0.157179
Name: age, dtype: float64

In [121]:
# Pandas read_csv from url

url = "https://raw.githubusercontent.com/bforoura/IDS/main/alcohol_deaths.csv"

df2 = pd.read_csv(url, sep=",")

In [122]:
# display info about df2 attributes and their types

df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21 entries, 0 to 20
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Country  21 non-null     object
 1   Alcohol  21 non-null     float64
 2   Deaths   21 non-null     int64
 3   Heart    19 non-null     float64
 4   Liver    20 non-null     float64
dtypes: float64(3), int64(1), object(1)
memory usage: 968.0+ bytes

In [123]:
# display the entire data frame

df2

           Country  Alcohol  Deaths  Heart      Liver
0        Australia     2.50     785  211.0  15.300000
1          Austria     3.00     863  167.0  45.599998
2   Belg. and Lux.     2.90     883  131.0  20.700001
3           Canada     2.40     793    NaN  16.400000
4          Denmark     2.90     971  220.0  23.900000
5          Finland     0.80     970  297.0  19.000000
6           France     9.10     751   11.0  37.900002
7          Iceland    -0.80     743  211.0  11.200000
8          Ireland     0.70    1000  300.0   6.500000
9           Israel     0.60    -834  183.0  13.700000
10           Italy    27.90     775  107.0  42.200001
11           Japan     1.50     680   36.0  23.200001
12     Netherlands     1.80     773  167.0   9.200000
13     New Zealand     1.90     916  266.0   7.700000
14          Norway     0.08     806  227.0  12.200000
15           Spain     6.50     724    NaN        NaN
16          Sweden     1.60     743  207.0  11.200000
17     Switzerland     5.80     693  115.0  20.299999
18              UK     1.30     941  285.0  10.300000
19              US     1.20     926  199.0  22.100000
20    West Germany     2.70     861  172.0  36.700001

In [124]:
# print size of columns and rows in the data frame

df2.shape

(21, 5)

In [125]:
# find the mean of the Heart column

df2['Heart'].mean()

184.8421052631579

In [126]:
# are there any non-number (missing) values in this column?

df2['Heart'].isna()

0     False
1     False
2     False
3      True
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15     True
16    False
17    False
18    False
19    False
20    False
Name: Heart, dtype: bool

In [127]:
# Fill NaN Values in the Heart Column with the Mean value (impute)

df2['Heart'] = df2['Heart'].fillna(df2['Heart'].mean())

In [128]:
# Remove negative values for Alcohol

df2['Alcohol'] = df2['Alcohol'].abs()

In [129]:
# examine the partially cleansed data

df2

           Country  Alcohol  Deaths       Heart      Liver
0        Australia     2.50     785  211.000000  15.300000
1          Austria     3.00     863  167.000000  45.599998
2   Belg. and Lux.     2.90     883  131.000000  20.700001
3           Canada     2.40     793  184.842105  16.400000
4          Denmark     2.90     971  220.000000  23.900000
5          Finland     0.80     970  297.000000  19.000000
6           France     9.10     751   11.000000  37.900002
7          Iceland     0.80     743  211.000000  11.200000
8          Ireland     0.70    1000  300.000000   6.500000
9           Israel     0.60    -834  183.000000  13.700000
10           Italy    27.90     775  107.000000  42.200001
11           Japan     1.50     680   36.000000  23.200001
12     Netherlands     1.80     773  167.000000   9.200000
13     New Zealand     1.90     916  266.000000   7.700000
14          Norway     0.08     806  227.000000  12.200000
15           Spain     6.50     724  184.842105        NaN
16          Sweden     1.60     743  207.000000  11.200000
17     Switzerland     5.80     693  115.000000  20.299999
18              UK     1.30     941  285.000000  10.300000
19              US     1.20     926  199.000000  22.100000
20    West Germany     2.70     861  172.000000  36.700001

In [130]:
# Let's add the wrangled data for India

df2.append({'Country': 'India', 'Alcohol':2.53, 'Deaths': 'NA', 'Heart': 171, 'Liver': 'NA'}, ignore_index=True)

<ipython-input-130-aa5e498233bc>:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df2.append({'Country': 'India', 'Alcohol':2.53, 'Deaths': 'NA', 'Heart': 171, 'Liver': 'NA'}, ignore_index=True)

           Country  Alcohol Deaths       Heart      Liver
0        Australia     2.50    785  211.000000       15.3
1          Austria     3.00    863  167.000000  45.599998
2   Belg. and Lux.     2.90    883  131.000000  20.700001
3           Canada     2.40    793  184.842105       16.4
4          Denmark     2.90    971  220.000000       23.9
5          Finland     0.80    970  297.000000       19.0
6           France     9.10    751   11.000000  37.900002
7          Iceland     0.80    743  211.000000       11.2
8          Ireland     0.70   1000  300.000000        6.5
9           Israel     0.60   -834  183.000000       13.7
10           Italy    27.90    775  107.000000  42.200001
11           Japan     1.50    680   36.000000  23.200001
12     Netherlands     1.80    773  167.000000        9.2
13     New Zealand     1.90    916  266.000000        7.7
14          Norway     0.08    806  227.000000       12.2
15           Spain     6.50    724  184.842105        NaN
16          Sweden     1.60    743  207.000000       11.2
17     Switzerland     5.80    693  115.000000  20.299999
18              UK     1.30    941  285.000000       10.3
19              US     1.20    926  199.000000       22.1
20    West Germany     2.70    861  172.000000  36.700001
21           India     2.53     NA  171.000000         NA

In [131]:

"""  Discretize Alcohol

o	0: less than or equal to 1.00 per capita
o	1: more than 1.00 but less than or equal to 2.00 per capita
o	2: more than 2.00 but less than or equal to 5.00 per capita
o	3: more than 5.00 per capita

"""

df2['Alcohol'] = pd.cut(x=df2['Alcohol'], bins=[0, 1, 2, 5, 100], labels = [0, 1, 2, 3])

df2

           Country Alcohol  Deaths       Heart      Liver
0        Australia       2     785  211.000000  15.300000
1          Austria       2     863  167.000000  45.599998
2   Belg. and Lux.       2     883  131.000000  20.700001
3           Canada       2     793  184.842105  16.400000
4          Denmark       2     971  220.000000  23.900000
5          Finland       0     970  297.000000  19.000000
6           France       3     751   11.000000  37.900002
7          Iceland       0     743  211.000000  11.200000
8          Ireland       0    1000  300.000000   6.500000
9           Israel       0    -834  183.000000  13.700000
10           Italy       3     775  107.000000  42.200001
11           Japan       1     680   36.000000  23.200001
12     Netherlands       1     773  167.000000   9.200000
13     New Zealand       1     916  266.000000   7.700000
14          Norway       0     806  227.000000  12.200000
15           Spain       3     724  184.842105        NaN
16          Sweden       1     743  207.000000  11.200000
17     Switzerland       3     693  115.000000  20.299999
18              UK       1     941  285.000000  10.300000
19              US       1     926  199.000000  22.100000
20    West Germany       2     861  172.000000  36.700001

### **Extra Credit**

1. Replace the negative numbers in **Alcohol** and **Deaths** with their absolute values
2. Impute all missing values using column means
3. Discretize **Deaths** using your own judgment
4. Display the modified dataframe